name: svn
version: 1.0.1
appVersion: 5.2.4
description:  Subversion Edge Server is a svn repository with manage UI
keywords:
  - svn
  - subversion
  - subversioneage
  - repository
home: https://github.com/ftab/chart-svn
sources:
  - https://hub.docker.com/r/xps2/subversion-edge
maintainers:
  - name: ftab
    email: dennisf@radiosound.com
